@startuml

class LandPicker {
}

class TerrainInfo {
}

class DerivedStats {
}

class VerticalSplitter {
}

class Checkbox {
}

class CombinedArmsIcon {
}
CombinedArmsIcon *-- Image

class CombinedArms {
}
CombinedArms *-- CombinedArmsIcon

class Brigade {
}
Brigade *-- Button
Brigade *-- Image

class FormationBrigades {
}
FormationBrigades *-- Brigade

class FormationCost {
}

class FormationStatsBox {

}
FormationStatsBox *-- Checkbox
FormationStatsBox *-- CombinedArms
FormationStatsBox *-- FormationCost

class FormationInfo {
}
FormationInfo *-- FormationBrigades
FormationInfo *-- FormationStatsBox


class DivisionStatCell {
}
DivisionStatCell *-- Image

class DivisionStatColumn {
}
DivisionStatColumn *-- DivisionStatCell

class DivisionBasicStats {
}
DivisionBasicStats *-- VerticalSplitter
DivisionBasicStats *-- FormationInfo
DivisionBasicStats *-- DivisionStatColumn

class DivisionInfo {
}
DivisionInfo *-- DivisionBasicStats
DivisionInfo *-- TerrainInfo
DivisionInfo *-- DerivedStats

class DivisionBuilder {
}
DivisionBuilder *-- LandPicker
DivisionBuilder *-- DivisionInfo

' Uncomment to show component relationships
'!include InputComponents.puml!0
'!include InputComponents.puml!division
!include resize-components.puml!0
!include resize-components.puml!division

@enduml