@startuml

class HorizontalNav {
  Array<Component>: items
}

class Button {
}

class ImageButton {
}
ImageButton --|> Button

class InfoRepeater {
}

class FullScreenOverlay {
}

class DropDownMenu {
}
DropDownMenu *-- FullScreenOverlay

class ProductionMenu {
}
ProductionMenu *-- DropDownMenu
ProductionMenu *-- ImageButton

class TechMenuButton {
}
TechMenuButton --|> ImageButton

class Hoi3sMainNav {
}
Hoi3sMainNav *-- TechMenuButton
Hoi3sMainNav *-- InfoRepeater
Hoi3sMainNav *-- ProductionMenu
Hoi3sMainNav --|> HorizontalNav

' Uncomment to show component relationships
'!include InputComponents.puml!0
'!include InputComponents.puml!menu
'!include resize-components.puml!0
'!include resize-components.puml!menu

@enduml